CREATE DATABASE test_board;

USE test_board;

CREATE TABLE boards (
	id INT PRIMARY KEY AUTO_INCREMENT
	, title VARCHAR(30) NOT NULL
	, content VARCHAR(1000) NOT NULL
	, select_at DATETIME NOT NULL
	, create_at DATETIME DEFAULT CURRENT_TIMESTAMP()
	, update_at DATETIME DEFAULT NULL
	, delete_at DATETIME DEFAULT NULL
	, weather CHAR(1) NOT NULL
	, mood CHAR(1) NOT NULL
);